### ISSUE TITLE
update relative when scrollbar is disabled

### ISSUE THREAD

**Issue by hmuenzer** [wieringen/tinyscrollbar#19]
I use update 'relative' to keep the current position of the thumb after dynamically changes of the content.

When the size of the overview does not exceed the viewport, the scrollbar is disabled automatically (as desired), but...
- the overview is positioned bottom of the viewport (vertical scrollbar)
- the overview is positioned right aligned (horizontal scrollbar)

If I change the window size, the tinyscrollbar keeps this "wrong" position by changing the left/top position although the scrollbar is disabled.

In my opinion the script should align the overview top/left as soon, as the scrollbar is disabled (on any kind of update method).

I noticed this after I updated to the current version, so I guess it's a bug.

**Comment by AnilMj7** [comment]
i am not able to update the tiny scroll to relative position. it is either updating to top or bottom.
