### ISSUE TITLE
Bug in Firefox on Mac OS X

### ISSUE THREAD

**Issue by dmongeau** [wieringen/tinyscrollbar#52]
There is a bug with the line 210 at least in Firefox using a trackpad from a Macbook pro:
```javascript
wheelSpeedDelta = -(evntObj.deltaY || evntObj.detail || (-1 / 3 * evntObj.wheelDelta)) / 40
```

When `evntObj.deltaY` is equals to 0, it goes to `evntObj.detail` which is also equals to 0, which goes to `(-1 / 3 * evntObj.wheelDelta)` returning a `NaN`.

Also only the `deltaY` is used even if the axis is set to `x`.

Here is a pull request that correct this issue:
https://github.com/wieringen/tinyscrollbar/pull/51

**Comment by dmongeau** [comment]
Any updates on this?

**Comment by zrain** [comment]
if( isNaN(wheelDelta) ){
       wheelDelta = -(evntObj.deltaY / 40);
 }

**Comment by charlenelu** [comment]
Thanks for  @zrain, i`ve fixed using the code.
