### ISSUE TITLE
Drag not Working in Firefox 40.0.3 OSX 10.9.5

### ISSUE THREAD

**Issue by corsachriz** [wieringen/tinyscrollbar#61]
Scrolling works fine, but you cant use it dragging the thumb on the scroll bar, it just wont move.
(Tried on http://baijs.com/tinyscrollbar/)
Any fixes for that?

**Comment by inovek** [comment]
Is this issue still up to date? (It seems working with 41.0.1 under OSX 10.10.5)

**Comment by charlenelu** [comment]
Any fixes? I face the same problem..

**Comment by CodeFella** [comment]
Not working with Firefox 42.0, worked it down to function _wheel(event)

under some conditions the wheeldelta is NaN (just for one event) and therefore the self.contentPositioni getting invalid making the scrollbar stuck.

fixed the problem by wrapping the calculation of self.position 

 if (!isNaN(wheelDelta)) {
                    self.contentPosition -= wheelDelta * multiply * self.options.wheelSpeed;
                    self.contentPosition = Math.min((self.contentSize - self.viewportSize), Math.max(0, self.contentPosition));
                }
